name: 'failure Slack message'
description: 'Sends a slack message to notify of failure'
inputs:
  title:
    description: "Title of the failed workflow"
    required: true
  channel_id:
    description: "Slack channel to send to"
    required: true
  SLACK_BOT_TOKEN:
    description: "Important slack token"
    required: true
runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@v2.0.0
      with:
        channel-id: ${{ inputs.channel_id }}
        payload: |
          {
            "text": ":warning: *${{ inputs.title }}* Warning: Workflow *${{ github.workflow }}* failed!",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ inputs.warningOnly == 'true' && ':warning:' || ':no_entry:' }} Github Workflow ${{ github.workflow }} ${{ inputs.warningOnly == 'true' && 'ran and identified issues' || 'failed' }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Workflow:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Job:* ${{ github.job }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}